{{- $fullName := include "lemmy.fullname" . -}}
{{- with .Values.pictrs.storage -}}
{{- if eq .kind "persistentVolumeClaim" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-pictrs-data
  namespace: {{ $.Release.Namespace }}
spec:
  {{ if .pvc.storageClassName -}}
  storageClassName: {{ .pvc.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .pvc.size }}
{{- end -}}
{{- end }}
